# docker-compose.test.yml
# Simple configuration for testing published images

version: '3.8'

services:
  # Test CPU image
  test-cpu:
    image: ${DOCKER_HUB_USERNAME:-your-username}/ros-dev:${ROS_DISTRO:-humble}-cpu
    container_name: ros-test-cpu
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DISTRO=${ROS_DISTRO:-humble}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./test-workspace:/workspace/test_ws
    tty: true
    stdin_open: true
    profiles: ["test-cpu"]

  # Test GPU image
  test-gpu:
    image: ${DOCKER_HUB_USERNAME:-your-username}/ros-dev:${ROS_DISTRO:-humble}-gpu
    container_name: ros-test-gpu
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DISTRO=${ROS_DISTRO:-humble}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./test-workspace:/workspace/test_ws
    devices:
      - /dev/dri:/dev/dri
    tty: true
    stdin_open: true
    profiles: ["test-gpu"]

# Quick test runner
  quick-test:
    image: ${DOCKER_HUB_USERNAME:-your-username}/ros-dev:${ROS_DISTRO:-humble}-cpu
    container_name: ros-quick-test
    command: >
      bash -c "
        echo 'Testing ROS installation...' &&
        source /opt/ros/${ROS_DISTRO:-humble}/setup.bash &&
        if [ '${ROS_DISTRO:-humble}' = 'noetic' ]; then
          rosversion -d;
        else
          ros2 --version;
        fi &&
        echo 'ROS test completed successfully!'
      "
    profiles: ["quick-test"]
