version: '3.8'

services:
  ros-dev:
    build:
      context: .
      dockerfile: docker/compose/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:-humble}
        ENABLE_GPU: ${ENABLE_GPU:-false}
        CUDA_VERSION: ${CUDA_VERSION:-12.2}
        UBUNTU_VERSION: ${UBUNTU_VERSION:-22.04}
    
    image: ros-dev:${ROS_DISTRO:-humble}-${ENABLE_GPU:-cpu}
    container_name: ros-dev-${ROS_DISTRO:-humble}
    hostname: ros-dev
    
    # Conditional runtime - only set if GPU enabled
    runtime: ${GPU_RUNTIME:-}
    
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DISTRO=${ROS_DISTRO:-humble}
      # Only set NVIDIA vars if GPU enabled
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-}
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./workspaces/ros_ws:/workspace/ros_ws
      - ./workspaces/catkin_ws:/workspace/catkin_ws
      - ./workspaces/colcon_ws:/workspace/colcon_ws
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh:ro
      - ./docker/.bash_history:/root/.bash_history
    
    devices:
      - /dev:/dev
    
    privileged: true
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped
    
    # Conditional health check based on ROS version
    healthcheck:
      test: >
        if [ "${ROS_DISTRO}" = "noetic" ]; then
          rosnode list 2>/dev/null || echo "ROS1 not ready"
        else
          ros2 node list 2>/dev/null || echo "ROS2 not ready"
        fi
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Service profiles for different ROS distros
  ros-dev-noetic:
    extends:
      service: ros-dev
    build:
      args:
        ROS_DISTRO: noetic
        UBUNTU_VERSION: 20.04
    container_name: ros-dev-noetic
    profiles: ["noetic"]

  ros-dev-jazzy:
    extends:
      service: ros-dev
    build:
      args:
        ROS_DISTRO: jazzy
        UBUNTU_VERSION: 24.04
    container_name: ros-dev-jazzy
    profiles: ["jazzy"]

volumes:
  ros_logs:
    driver: local
